# RSI(14) пересек 30 вниз - лонг лимитка на лой этой свечки. выход 4-16 свечек.

In [1]:
from simple.binance import getHistMonth
from simple.plotly import chartFigure
from simple.pretty import pp, pmap
import pandas as pd
import numpy as np
from talib import RSI
from functools import partial
import plotly.graph_objects as go
from plotly.subplots import make_subplots

In [2]:
frame = '1h'
period = 14
threshold = 30
duration = 8
fee = 0.08
tickers = ['XRPUSDT', 'BTCUSDT', 'LTCUSDT', 'BNBUSDT', 'ZECUSDT', 'ETHUSDT']

In [3]:
def getOHLC(ticker: str) -> pd.Series:
    X = getHistMonth('2022-01', '2022-05', ticker, frame)[['Open', 'High', 'Low', 'Close', 'Volume']]
    X.columns = pd.MultiIndex.from_product([[ticker], X.columns])
    return X

In [4]:
F = pd.concat(pmap(getOHLC, tickers), axis=1)
F

  0%|          | 0/6 [00:00<?, ?it/s]

                    XRPUSDT                                       BTCUSDT  \
                       Open    High     Low   Close      Volume      Open
DT
2022-01-01 00:00:00  0.8294  0.8397  0.8293  0.8392  15673341.8  46210.57
2022-01-01 01:00:00  0.8392  0.8530  0.8313  0.8396  53241386.8  46650.00
2022-01-01 02:00:00  0.8395  0.8445  0.8391  0.8423  10609918.2  46767.44
2022-01-01 03:00:00  0.8424  0.8456  0.8405  0.8410   7823072.9  46796.15
2022-01-01 04:00:00  0.8409  0.8431  0.8343  0.8347  11611660.4  46789.55
...                     ...     ...     ...     ...         ...       ...
2022-05-31 19:00:00  0.4129  0.4158  0.4119  0.4142  20339633.1  31671.70
2022-05-31 20:00:00  0.4143  0.4199  0.4143  0.4197  17476597.6  31618.50
2022-05-31 21:00:00  0.4197  0.4212  0.4183  0.4206  18208857.1  31804.30
2022-05-31 22:00:00  0.4207  0.4248  0.4199  0.4248  25462708.5  31714.80
2022-05-31 23:00:00  0.4247  0.4255  0.4203  0.4213  25760082.2  31856.20

                                                              ... ZECUSDT  \
                         High       Low     Close     Volume  ...    Open
DT                                                            ...
2022-01-01 00:00:00  46729.73  46210.55  46650.01   8957.465  ...  146.38
2022-01-01 01:00:00  46944.56  46570.34  46766.78   7276.249  ...  148.39
2022-01-01 02:00:00  46917.87  46709.44  46796.14   4478.713  ...  147.87
2022-01-01 03:00:00  46888.00  46746.32  46789.56   4208.992  ...  148.06
2022-01-01 04:00:00  46868.74  46605.00  46690.81   6149.298  ...  147.82
...                       ...       ...       ...        ...  ...     ...
2022-05-31 19:00:00  31779.00  31569.00  31618.90  14481.731  ...   92.17
2022-05-31 20:00:00  31804.30  31586.20  31804.30   7666.311  ...   92.24
2022-05-31 21:00:00  31830.80  31648.00  31714.80   5821.417  ...   93.08
2022-05-31 22:00:00  31889.00  31673.30  31856.30   8372.720  ...   92.91
2022-05-31 23:00:00  31932.30  31763.20  31797.80   7116.994  ...   93.90

                                                        ETHUSDT           \
                       High     Low   Close     Volume     Open     High
DT
2022-01-01 00:00:00  148.54  146.36  148.39  11568.864  3676.01  3730.00
2022-01-01 01:00:00  148.98  147.56  147.87  11611.272  3721.67  3747.78
2022-01-01 02:00:00  148.34  147.77  148.04   7218.923  3723.72  3735.42
2022-01-01 03:00:00  148.28  147.65  147.82   9526.273  3727.04  3734.62
2022-01-01 04:00:00  147.99  146.38  146.64  12099.816  3722.07  3726.63
...                     ...     ...     ...        ...      ...      ...
2022-05-31 19:00:00   92.86   91.71   92.22  30823.617  1933.84  1944.46
2022-05-31 20:00:00   93.68   92.10   93.07  19779.510  1933.82  1953.62
2022-05-31 21:00:00   93.37   92.37   92.93   8816.692  1952.91  1953.58
2022-05-31 22:00:00   94.02   92.73   93.91  19030.718  1947.38  1959.69
2022-05-31 23:00:00   94.28   92.99   93.19  19363.211  1956.08  1957.74


                         Low    Close      Volume
DT
2022-01-01 00:00:00  3676.01  3721.67   45835.920
2022-01-01 01:00:00  3712.65  3723.71   39219.106
2022-01-01 02:00:00  3721.15  3727.03   18603.210
2022-01-01 03:00:00  3720.56  3722.07   12613.551
2022-01-01 04:00:00  3706.00  3707.30   27995.465
...                      ...      ...         ...
2022-05-31 19:00:00  1926.78  1933.76  100139.057
2022-05-31 20:00:00  1933.65  1952.91   57194.301
2022-05-31 21:00:00  1941.21  1947.37   31483.261
2022-05-31 22:00:00  1941.82  1956.08   63343.738
2022-05-31 23:00:00  1937.15  1941.68   49423.136

[3624 rows x 30 columns]

In [5]:
C = F.BTCUSDT.copy()
C['RSI'] = RSI(C.Close, period)

def enterLong(row, threshold):
    return 1 if row[0] > threshold and row[1] < threshold else 0

C['Target'] = C.RSI.rolling(window=2).apply(partial(enterLong, threshold=threshold)).shift()
C['PrevLow'] = C.Low.shift()
C

,Open,High,Low,Close,Volume,RSI,Target,PrevLow
DT,,,,,,,,
2022-01-01 00:00:00,46210.57,46729.73,46210.55,46650.01,8957.465,NaN,NaN,NaN
2022-01-01 01:00:00,46650.00,46944.56,46570.34,46766.78,7276.249,NaN,NaN,46210.55
2022-01-01 02:00:00,46767.44,46917.87,46709.44,46796.14,4478.713,NaN,NaN,46570.34
2022-01-01 03:00:00,46796.15,46888.00,46746.32,46789.56,4208.992,NaN,NaN,46709.44
2022-01-01 04:00:00,46789.55,46868.74,46605.00,46690.81,6149.298,NaN,NaN,46746.32
...,...,...,...,...,...,...,...,...
2022-05-31 19:00:00,31671.70,31779.00,31569.00,31618.90,14481.731,53.854644,0.0,31562.00
2022-05-31 20:00:00,31618.50,31804.30,31586.20,31804.30,7666.311,57.823229,0.0,31569.00
2022-05-31 21:00:00,31804.30,31830.80,31648.00,31714.80,5821.417,55.348588,0.0,31586.20
2022-05-31 22:00:00,31714.80,31889.00,31673.30,31856.30,8372.720,58.381204,0.0,31648.00
2022-05-31 23:00:00,31856.20,31932.30,31763.20,31797.80,7116.994,56.667636,0.0,31673.30

In [6]:
Pos = np.zeros(len(C))
for index, row in enumerate(C.itertuples(index=False)):
    if row.Target > 0 and row.Low < row.PrevLow:
        Pos[index:index+duration] = 1
        
C['Pos'] = Pos
C['DPos'] = C.Pos.diff()
C['Money'] = (-C.DPos * C.Low).cumsum()
C['Fee'] = (C.DPos * C.Open * fee / 100).abs().cumsum()
C['Balance'] = C.Money + C.Pos * C.Open
C

,Open,High,Low,Close,Volume,RSI,Target,PrevLow,Pos,DPos,Money,Fee,Balance
DT,,,,,,,,,,,,,
2022-01-01 00:00:00,46210.57,46729.73,46210.55,46650.01,8957.465,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN
2022-01-01 01:00:00,46650.00,46944.56,46570.34,46766.78,7276.249,NaN,NaN,46210.55,0.0,0.0,0.00,0.0000,0.00
2022-01-01 02:00:00,46767.44,46917.87,46709.44,46796.14,4478.713,NaN,NaN,46570.34,0.0,0.0,0.00,0.0000,0.00
2022-01-01 03:00:00,46796.15,46888.00,46746.32,46789.56,4208.992,NaN,NaN,46709.44,0.0,0.0,0.00,0.0000,0.00
2022-01-01 04:00:00,46789.55,46868.74,46605.00,46690.81,6149.298,NaN,NaN,46746.32,0.0,0.0,0.00,0.0000,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2022-05-31 19:00:00,31671.70,31779.00,31569.00,31618.90,14481.731,53.854644,0.0,31562.00,0.0,0.0,-2273.82,2113.2464,-2273.82
2022-05-31 20:00:00,31618.50,31804.30,31586.20,31804.30,7666.311,57.823229,0.0,31569.00,0.0,0.0,-2273.82,2113.2464,-2273.82
2022-05-31 21:00:00,31804.30,31830.80,31648.00,31714.80,5821.417,55.348588,0.0,31586.20,0.0,0.0,-2273.82,2113.2464,-2273.82
2022-05-31 22:00:00,31714.80,31889.00,31673.30,31856.30,8372.720,58.381204,0.0,31648.00,0.0,0.0,-2273.82,2113.2464,-2273.82
2022-05-31 23:00:00,31856.20,31932.30,31763.20,31797.80,7116.994,56.667636,0.0,31673.30,0.0,0.0,-2273.82,2113.2464,-2273.82

In [7]:
Buy = C[C.DPos > 0]
Sell = C[C.DPos < 0]

In [8]:
fig = go.FigureWidget(make_subplots(rows=3, cols=1, shared_xaxes=True, vertical_spacing=0,
                                    row_heights=[0.7, 0.15, 0.15], specs=[[{"secondary_y": True}], [{}], [{}]]))

fig.update_layout(autosize=True, height=800, template='plotly_white',
                  legend=dict(x=0.1, y=1.01, orientation="h"),
                  margin=dict(l=45, r=5, b=10, t=10, pad=3),
                  xaxis_rangeslider_visible=False,
                  yaxis2_showgrid=False)

fig.add_candlestick(x=C.index, open=C.Open, high=C.High, low=C.Low, close=C.Close, name='OHLC', opacity=0.5)
fig.add_scattergl(name='Buy', mode='markers', x=Buy.index, y=Buy.PrevLow, marker=dict(symbol='triangle-up', color='green', size=10)) 
fig.add_scattergl(name='Sell', mode='markers', x=Sell.index, y=Sell.Open, marker=dict(symbol='triangle-down', color='red', size=10))

fig.add_trace(go.Scattergl(x=C.index, y=C.Balance, name='Balance', line_color='blue', connectgaps=True, line_shape='hv'), secondary_y=True)
fig.add_trace(go.Scattergl(x=C.index, y=C.Fee, name='Fee', line_color='red', connectgaps=True), secondary_y=True)

fig.add_scattergl(name='RSI', x=C.index, y=C.RSI, row=2, col=1)
fig.add_bar(name='Long', x=C.index, y=C.Pos, marker_color='green', row=3, col=1, opacity=0.5)
fig.add_scattergl(x=C.index, y=C.Target/2, name='Target', row=3, col=1, line_color='green', connectgaps=True)

fig.update_xaxes(spikemode='across+marker', spikedash='dot', spikethickness=1, spikesnap='cursor')
fig.update_traces(xaxis='x1')
fig.update_xaxes(showgrid=True, title='Time', visible=True, showticklabels=True)

fig

FigureWidget({
    'data': [{'close': array([46650.01, 46766.78, 46796.14, ..., 31714.8 , 31856.3 , 31797.8 ])…