# RSI(14) пересек 30 вниз - лонг лимитка на лой этой свечки. выход 4-16 свечек.

In [1]:
from simple.binance import getHistMonth
from simple.plotly import chartFigure
from simple.pretty import pp, pmap
import pandas as pd
import numpy as np
from talib import RSI
from functools import partial
import plotly.graph_objects as go
from plotly.subplots import make_subplots

In [2]:
frame = '1h'
period = 14
threshold = 30
duration = 8
fee = 0.08
tickers = ['XRPUSDT', 'BTCUSDT', 'LTCUSDT', 'BNBUSDT', 'ZECUSDT', 'ETHUSDT']

In [3]:
def getOHLC(ticker: str) -> pd.Series:
    X = getHistMonth('2022-03', '2022-03', ticker, frame)[['Open', 'High', 'Low', 'Close', 'Volume']]
    X.columns = pd.MultiIndex.from_product([[ticker], X.columns])
    return X

In [4]:
F = pd.concat(pmap(getOHLC, tickers), axis=1)
F

  0%|          | 0/6 [00:00<?, ?it/s]

                    XRPUSDT                                      BTCUSDT  \
                       Open    High     Low   Close      Volume     Open
DT
2022-03-01 00:00:00  0.7808  0.7894  0.7783  0.7848  59288382.1  43155.0
2022-03-01 01:00:00  0.7848  0.7857  0.7704  0.7711  48061235.9  43548.6
2022-03-01 02:00:00  0.7710  0.7715  0.7636  0.7687  49285837.1  43254.1
2022-03-01 03:00:00  0.7688  0.7750  0.7662  0.7745  23449913.7  43149.4
2022-03-01 04:00:00  0.7745  0.7768  0.7726  0.7765  23698648.7  43140.9
...                     ...     ...     ...     ...         ...      ...
2022-03-31 19:00:00  0.8162  0.8242  0.8073  0.8121  47950007.9  45946.9
2022-03-31 20:00:00  0.8121  0.8166  0.8100  0.8161  17419526.9  45578.1
2022-03-31 21:00:00  0.8161  0.8212  0.8154  0.8173  14190355.9  45741.9
2022-03-31 22:00:00  0.8173  0.8217  0.8148  0.8188  14073198.7  45736.2
2022-03-31 23:00:00  0.8188  0.8203  0.8054  0.8146  30041818.8  45782.2

                                                           ... ZECUSDT  \
                        High      Low    Close     Volume  ...    Open
DT                                                         ...
2022-03-01 00:00:00  43790.0  43150.3  43548.7  24064.483  ...  118.51
2022-03-01 01:00:00  43615.3  43215.1  43254.1  12130.047  ...  119.98
2022-03-01 02:00:00  43294.7  42954.0  43148.9  14401.448  ...  119.13
2022-03-01 03:00:00  43190.0  42850.0  43140.8   9922.937  ...  117.66
2022-03-01 04:00:00  43401.6  43062.2  43323.5   9700.152  ...  116.48
...                      ...      ...      ...        ...  ...     ...
2022-03-31 19:00:00  45986.1  45469.3  45578.1  16711.045  ...  181.37
2022-03-31 20:00:00  45789.9  45506.6  45741.9   9730.602  ...  179.70
2022-03-31 21:00:00  45852.2  45638.1  45736.1   4531.138  ...  179.55
2022-03-31 22:00:00  45814.9  45646.7  45782.3   4252.388  ...  179.27
2022-03-31 23:00:00  45788.6  45185.0  45506.0  15820.137  ...  179.55

                                                        ETHUSDT           \
                       High     Low   Close     Volume     Open     High
DT
2022-03-01 00:00:00  120.27  118.15  119.97  28369.799  2920.05  2974.44
2022-03-01 01:00:00  120.05  118.73  119.12  14681.503  2947.45  2950.00
2022-03-01 02:00:00  119.28  117.27  117.72  23678.333  2917.26  2921.60
2022-03-01 03:00:00  117.72  115.83  116.48  15938.937  2917.23  2918.55
2022-03-01 04:00:00  118.30  116.40  117.97  14847.958  2911.82  2934.62
...                     ...     ...     ...        ...      ...      ...
2022-03-31 19:00:00  181.37  179.01  179.68  19356.832  3307.59  3310.69
2022-03-31 20:00:00  180.06  177.98  179.55  29836.616  3282.81  3302.93
2022-03-31 21:00:00  180.28  178.84  179.30  11829.907  3298.07  3305.32
2022-03-31 22:00:00  180.03  178.29  179.57  11451.580  3286.19  3291.77
2022-03-31 23:00:00  180.29  176.32  178.34  20280.147  3289.18  3296.05


                         Low    Close      Volume
DT
2022-03-01 00:00:00  2919.03  2947.44  186530.975
2022-03-01 01:00:00  2912.99  2917.25   78316.410
2022-03-01 02:00:00  2904.61  2917.35   70692.111
2022-03-01 03:00:00  2890.07  2911.82   64332.756
2022-03-01 04:00:00  2905.38  2924.33   55464.990
...                      ...      ...         ...
2022-03-31 19:00:00  3281.55  3282.42   73310.401
2022-03-31 20:00:00  3277.83  3298.07   52985.689
2022-03-31 21:00:00  3286.19  3286.20   23177.581
2022-03-31 22:00:00  3272.94  3289.17   42148.138
2022-03-31 23:00:00  3261.69  3281.43   69214.080

[744 rows x 30 columns]

In [5]:
C = F.BTCUSDT.copy()
C['RSI'] = RSI(C.Close, period)

def enterLong(row, threshold):
    return 1 if row[0] > threshold and row[1] < threshold else 0

C['Target'] = C.RSI.rolling(window=2).apply(partial(enterLong, threshold=threshold)).shift()
C

,Open,High,Low,Close,Volume,RSI,Target
DT,,,,,,,
2022-03-01 00:00:00,43155.0,43790.0,43150.3,43548.7,24064.483,NaN,NaN
2022-03-01 01:00:00,43548.6,43615.3,43215.1,43254.1,12130.047,NaN,NaN
2022-03-01 02:00:00,43254.1,43294.7,42954.0,43148.9,14401.448,NaN,NaN
2022-03-01 03:00:00,43149.4,43190.0,42850.0,43140.8,9922.937,NaN,NaN
2022-03-01 04:00:00,43140.9,43401.6,43062.2,43323.5,9700.152,NaN,NaN
...,...,...,...,...,...,...,...
2022-03-31 19:00:00,45946.9,45986.1,45469.3,45578.1,16711.045,27.864659,0.0
2022-03-31 20:00:00,45578.1,45789.9,45506.6,45741.9,9730.602,32.038895,1.0
2022-03-31 21:00:00,45741.9,45852.2,45638.1,45736.1,4531.138,31.968353,0.0
2022-03-31 22:00:00,45736.2,45814.9,45646.7,45782.3,4252.388,33.229466,0.0
2022-03-31 23:00:00,45782.2,45788.6,45185.0,45506.0,15820.137,29.685344,0.0

In [6]:
Pos = np.zeros(len(C))
for index, row in enumerate(C.itertuples(index=False)):
    if row.Target > 0 and row.Low < row.Open:
        Pos[index:index+duration] = 1
        
C['Pos'] = Pos
C['DPos'] = C.Pos.diff()
C['Money'] = (-C.DPos * C.Open).cumsum()
C['Fee'] = (C.DPos * C.Open * fee / 100).abs().cumsum()
C['Balance'] = C.Money + C.Pos * C.Open
C

,Open,High,Low,Close,Volume,RSI,Target,Pos,DPos,Money,Fee,Balance
DT,,,,,,,,,,,,
2022-03-01 00:00:00,43155.0,43790.0,43150.3,43548.7,24064.483,NaN,NaN,0.0,NaN,NaN,NaN,NaN
2022-03-01 01:00:00,43548.6,43615.3,43215.1,43254.1,12130.047,NaN,NaN,0.0,0.0,0.0,0.00000,0.0
2022-03-01 02:00:00,43254.1,43294.7,42954.0,43148.9,14401.448,NaN,NaN,0.0,0.0,0.0,0.00000,0.0
2022-03-01 03:00:00,43149.4,43190.0,42850.0,43140.8,9922.937,NaN,NaN,0.0,0.0,0.0,0.00000,0.0
2022-03-01 04:00:00,43140.9,43401.6,43062.2,43323.5,9700.152,NaN,NaN,0.0,0.0,0.0,0.00000,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
2022-03-31 19:00:00,45946.9,45986.1,45469.3,45578.1,16711.045,27.864659,0.0,1.0,0.0,-45850.4,541.48928,96.5
2022-03-31 20:00:00,45578.1,45789.9,45506.6,45741.9,9730.602,32.038895,1.0,1.0,0.0,-45850.4,541.48928,-272.3
2022-03-31 21:00:00,45741.9,45852.2,45638.1,45736.1,4531.138,31.968353,0.0,1.0,0.0,-45850.4,541.48928,-108.5
2022-03-31 22:00:00,45736.2,45814.9,45646.7,45782.3,4252.388,33.229466,0.0,1.0,0.0,-45850.4,541.48928,-114.2
2022-03-31 23:00:00,45782.2,45788.6,45185.0,45506.0,15820.137,29.685344,0.0,1.0,0.0,-45850.4,541.48928,-68.2

In [7]:
Buy = C[C.DPos > 0]
Sell = C[C.DPos < 0]

In [39]:
fig = go.FigureWidget(make_subplots(rows=3, cols=1, shared_xaxes=True, vertical_spacing=0,
                                    row_heights=[0.7, 0.15, 0.15], specs=[[{"secondary_y": True}], [{}], [{}]]))

fig.update_layout(autosize=True, height=800, template='plotly_white',
                  legend=dict(x=0.4, y=1.01, orientation="h"),
                  margin=dict(l=45, r=5, b=10, t=10, pad=3),
                  xaxis_rangeslider_visible=False,
                  yaxis2_showgrid=False)

fig.add_candlestick(x=C.index, open=C.Open, high=C.High, low=C.Low, close=C.Close, name='OHLC', opacity=0.5)
fig.add_scattergl(name='Buy', mode='markers', x=Buy.index, y=Buy.Open, marker=dict(symbol='triangle-up', color='green', size=10)) 
fig.add_scattergl(name='Sell', mode='markers', x=Sell.index, y=Sell.Open, marker=dict(symbol='triangle-down', color='red', size=10))

fig.add_trace(go.Scattergl(x=C.index, y=C.Balance, name='Balance', line_color='blue', connectgaps=True, line_shape='hv'), secondary_y=True)
fig.add_trace(go.Scattergl(x=C.index, y=C.Fee, name='Fee', line_color='red', connectgaps=True), secondary_y=True)

fig.add_scattergl(name='RSI', x=C.index, y=C.RSI, row=2, col=1)
fig.add_bar(name='Long', x=C.index, y=C.Pos, marker_color='green', row=3, col=1, opacity=0.5)
fig.add_scattergl(x=C.index, y=C.Target/2, name='Target', row=3, col=1, line_color='green', connectgaps=True)

fig.update_xaxes(spikemode='across+marker', spikedash='dot', spikethickness=1, spikesnap='cursor')
fig.update_traces(xaxis='x1')
fig.update_xaxes(showgrid=True, title='Time', visible=True, showticklabels=True)

fig

FigureWidget({
    'data': [{'close': array([43548.7, 43254.1, 43148.9, ..., 45736.1, 45782.3, 45506. ]),
    …